id: P5C34579F
initial_creation_type: ocr
source_metadata:
  volumes:
    e0bfa0fcb8d04a81b8f0de3a492f694d:
      base_file: v073.txt
      image_group_id: I1PD95918
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་བྱང་ཆུབ་སེམས་དཔའི་ས།
      total_pages: 1125
      volume_number: 73
